live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[env]
TERM = "xterm-256color"
